### ISSUE TITLE
The list of expected errors is not configurable

### ISSUE THREAD

**Issue by nlarew** [cbush/snooty-autobuilder-check#1]
The autobuilder check can ignore errors messages based on a list of regular expressions. Currently the list is [hardcoded](https://github.com/cbush/snooty-autobuilder-check/blob/main/src/index.ts#L9) in `index.ts` and includes errors specific to the MongoDB Realm docs.

We should update this action to accept `expectedErrors` as a configuration parameter instead of hardcoding so that other projects can define their own errors.

**Comment by cbush** [comment]
https://github.com/cbush/snooty-autobuilder-check/pull/4
